### PR TITLE
Remove meta from join list

### PR DESCRIPTION
**Pull request by MineRobber9000**
You don't have permission to put k in #meta, so stop trying to put k in #meta.

### CODE REVIEW

**Comment by xfnw** [comment]
is this pr even needed? its banned from meta anyways

**Comment by MineRobber9000** [comment]
I mean, it'll save the bot the computation cycles of sending the JOIN command to a channel it's banned from. It's an optimization.

**Comment by kiedtl** [comment]
Has the bot created any spam? @MineRobber9000

**Comment by MineRobber9000** [comment]
You don't understand. You have to actually **get permission** before tossing a bot in #meta. You can't just be like "I'm not making any spam so its good".

Also, yes, you have created spam. You blind-messaged neko about your reimplementation of oven (which was a ripoff of badger anyways.) That's not cool.

You need permission from an IRCOp before putting a bot in #meta, and you've made a horrible first impression.

**Comment by kiedtl** [comment]
As I've remarked in #meta,

- I had permission. Written permission
- Fair enough, it created spam. That will be fixed very soon (tomorrow at latest).

**Comment by MineRobber9000** [comment]
You had permission for #team, not #meta. Are you dyslexic? If so, I'm sorry for making fun of you.

The logs show you have permission for k in #team. If you have an email showing you have perms for k in #meta, then show it (ben's online right now).

**Comment by xfnw** [comment]
> Has the bot created any spam? @MineRobber9000 

yes

**Comment by xfnw** [comment]
> - Fair enough, it created spam. That will be fixed very soon (tomorrow at latest).

then why was it in meta before tomorrow lol

**Comment by kiedtl** [comment]
Due to a misunderstanding k was put into meta while it only had permission for the teams channel.


I'm going to leave this open until I receive an explicit approval or disapproval from ben. In the mean time, the bot will stay only on the bots channel.

**Comment by kiedtl** [comment]
The disapproval has been received. However, as I already removed #meta from the channel list, this PR is unnecessary and will be closed.

**Pull request closed without merging**
